---
title: "Legal Matters"
papersize: A4
format:
  html: 
    toc-depth: 3
  epub: default
  docx: 
    toc-depth: 3
  pdf:
    colorlinks: true
    latex: 
       - lof: true
editor: visual
toc: true
lang: en-GB
---

# Welcome!

This document is divided into two parts:

1.  **Information Regarding Your Contract and NDA with Reprex**: This section is designed to also familiarize you with the basic workflows of GitHub.

2.  **Guidance on Setting Up a Self-Employed Legal Status in Hungary and Managing Invoices and Taxes Correctly**: As this pertains to Hungarian law, this chapter will be presented in the Hungarian language.

    ## 1. Information Regarding Your Contract and NDA with Reprex

To onboard, you need to sign an NDA (Non Sisclosure Agreement) and a Contract with Reprex. Through this process you will also learn the basic workflows of Github, such as forking, cloning, commiting, pushing and pull requesting.

The process for both documents:

1\. Acces [this repository.](https://github.com/Eviota/NDA)

2\. Fork/Clone this repository.

3\. Through Github Desktop clone your fork to your local computer.

4\. Fill the documents with your relevant data.

5\. Commit the changes.

6\. Push/Pull request the changes for the documents.

7\. Wait for Feedback (RepRex will check your data and fill theirs)

8\. Download the updated documents.

9\. Sign the documents.

1\. Push/Pull request the changes for the documents.

2\. Wait for Feedback (RepRex will sign the documents).

3\. All done, now both parties can access the filled and signed documents.

<!--- komment --->

Now let's see in details:

\<!--- komment ---

```         
## 2. Guidance on Setting Up a Self-Employed Legal Status in Hungary and Managing Invoices and Taxes Correctly
```

\##
