# Welcome 👋

This repository contains information about our onboarding processes.

`Folders` appear like this in this repository.

To ensure a seamless onboarding experience, please follow these steps:

1.  Install Keybase to communicate with us and ask questions (find more information in the `Onboarding Materials` » `Communication Platforms` section).
2.  Familiarize yourself with the basic workflow of GitHub by completing the tasks outlined in the `Legal Matters` folder.
3.  <!--# others steps to complete -->
4.  Feel free to explore the repository, and if you have any questions, don't hesitate to reach out!

## Folder and file structure of the repository:

### `Onboarding Materials`

In this folder you can find all the relevant information for your onboarding process about:

`Communication platforms`: contains information about the platforms we use to cooperate (Keybase, Company Email Address, Todoist, Google Calendar)

`Legal Matters`: Includes information about your contract and NDA with Reprex, as well as guidance on setting up a self-employed legal status and managing invoices and taxes correctly.

`Technical Tools`: Provides resources and guides for tools such as GitHub, RStudio, Quarto, Wikibase, etc.

## Other Guides and Information

In this folder, you can find other relevant guides. This information might become handy while working with us.

## Data folders

We have two data folders:

`data-raw`: Raw, unprocessed data, as received, downloaded, collected

`data`: This folder contains the processed data or our outputs.

## Visualisation folders

We save visualisations in folders corresponding to the file format.

`png`: contains visualisations in Portable Network Graphics format (our preferred format.)

`jpg`: Contains visualization in Joint Photographic Experts Group format.

`doc:`
